### ISSUE TITLE
Please enhance code quality with below points. 

### ISSUE THREAD

**Issue by sraikwar1994** [Shubham8144/flaskapp#1]
- [x] please check below SS containing one comment, please remove it from the code. 

![image](https://user-images.githubusercontent.com/93920967/168226699-151e23e2-3c42-499c-810a-e25d23015906.png)

- [x] Add requirements.txt file in the project. 
- [x] Add one `.gitignore` file in project. 
- [x] Install `black` and `isort` package to check code formating and errors.

**Comment by Shubham8144** [comment]
all four done.
