### ISSUE TITLE
config.py file implementation is wrong. 

### ISSUE THREAD

**Issue by sraikwar1994** [Shubham8144/flaskapp#3]
https://github.com/Shubham8144/flaskapp/blob/e29df7eec6860743fd00f4a7917845fe70fb5c52/config.py#L3-L4

- [ ] App initiation is valid only in `app.py`. 
- [ ] `config.py` file only contains constants and config classes. follow below documentation. 

https://flask.palletsprojects.com/en/2.1.x/config/#configuration-best-practices

**Comment by Shubham8144** [comment]
done
