### ISSUE TITLE
Templates improvements

### ISSUE THREAD

**Issue by sraikwar1994** [Shubham8144/flaskapp#6]
https://github.com/Shubham8144/flaskapp/blob/e29df7eec6860743fd00f4a7917845fe70fb5c52/templates/index.html#L9
https://github.com/Shubham8144/flaskapp/blob/e29df7eec6860743fd00f4a7917845fe70fb5c52/templates/index.html#L9

- [x] Remove CDN URLs, download files and use them in the static directory. 
- [x] Use jinja templating for serving static files. 

https://github.com/Shubham8144/flaskapp/blob/e29df7eec6860743fd00f4a7917845fe70fb5c52/templates/index.html#L57-L61

- [x] Remove redundant/commented code 
- [x] Create `base.html` file and inherit in `index.html` file.

**Comment by Shubham8144** [comment]
done
